---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: prometheus-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
      - secrets
      - serviceaccounts
      - configmaps
      - services/finalizers
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - deletecollection
      - watch
  - apiGroups:
      - ""
    resources:
      - events
      - namespaces
      - nodes
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - deletecollection
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
      - podmonitors
      - prometheuses
      - alertmanagers
      - prometheusrules
      - thanosrulers
      - alertmanagerconfigs
      - probes
      - prometheuses/finalizers
      - alertmanagers/finalizers
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - deletecollection
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-operator
subjects:
  - kind: ServiceAccount
    name: prometheus-operator
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: prometheus-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: final-year-project
  name: prometheus-operator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus-application-operator
  template:
    metadata:
      labels:
        k8s-app: prometheus-application-operator
    spec:
      containers:
        - args:
            - --kubelet-service=kube-system/kubelet
            - --logtostderr=true
            - -log-level=warn
            - --prometheus-instance-namespaces=monitoring
            - --alertmanager-instance-namespaces=monitoring
          image: quay.io/coreos/prometheus-operator:v0.42.1
          name: prometheus-application-operator
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext: { }
      serviceAccountName: prometheus-operator
---
apiVersion: v1
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: default
    receivers:
    - name: default
kind: Secret
metadata:
  name: alertmanager-alertmanager
  namespace: monitoring
  type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: monitoring
spec:
  ports:
    - name: web
      port: 9093
      protocol: TCP
  selector:
    app: alertmanager
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
      - name: alertmanager-service
        namespace: monitoring
        port: web
        scheme: http
        bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        tlsConfig:
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          serverName: "alertmanager-service.monitoring.svc"
secrets:
  - prometheus-k8s-tls
  - prometheus-k8s-proxy
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  listenLocal: true
secrets:
  - alertmanager-k8s-tls
  - alertmanager-k8s-proxy
